### ISSUE TITLE
How to abort in multithreading?

### ISSUE THREAD

**Issue by nayaku** [ied206/Joveler.Compression#16]
When the stream is in a compressed state, I call the `Abort` function in another thread. it will be in the `Flush` function and always wait for `XZInit.Lib.LzmaCode` return.

**Comment by ied206** [comment]
XZ streams instance is not a thread-safe object.
MS usually designed .NET classes tend to be thread-safe in static methods, and not thread-safe in instance methods. My implementation follows the same policy.

When you want to use a single instance in multiple threads, you should lock it yourself.

Try [lock keyword](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock), it is very straightforward.

**Comment by nayaku** [comment]
OKay, thank you.
