### ISSUE TITLE
Location for native libs

### ISSUE THREAD

**Issue by zcsizmadia** [ied206/Joveler.Compression#2]
It would be great to store the native libs in ./runtimes/RID/native folder, just like any other dotnet core native library. Additionally if self contained published package is generated, only the proper lib should be in added to the published package (since the runtime platform is specified)

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders

**Comment by ied206** [comment]
Sorry for the late reply. I will research about how can I improve native library handling.

**Comment by ied206** [comment]
Please test [v4.0.0](https://github.com/ied206/Joveler.Compression/releases/tag/v4.0.0) release. Starting from this release, Joveler.Compression NuGet packages will use `runtimes/<RID>/native` directory for native libraries.

**Comment by zcsizmadia** [comment]
Thanks! I will give it a try later this week.

**Comment by ied206** [comment]
The changed directory structure only affects .NET Standard build of the library, such as .NET Core.

.NET Framework build still uses `x64` and `x86` directories because .NET Framework does not acknowledge `runtimes/<RID>/native` directories.
