### ISSUE TITLE
Not enough memory errors

### ISSUE THREAD

**Issue by markusmobius** [ied206/Joveler.Compression#3]
I am getting the following errors at times:

Joveler.Compression.XZ.XZException: Not enough memory

I am running on Windows x64. Is there some setting that allows me to avoid this error. I cannot catch it.

**Comment by ied206** [comment]
@markusmobius Please provide the config you used (compress or decompress, thread count, compress level, etc.).
XZ tends to use lots of memory when high thread count and high compress level are combined.

**Comment by ied206** [comment]
Closing the issue due to lack of information.
