### ISSUE TITLE
nuget error NU3034

### ISSUE THREAD

**Issue by TomCJones** [ied206/Joveler.Compression#6]
what can i do to avoid ==>    Error	NU3034	Package 'Joveler.DynLoader 2.1.0' from source 'https://api.nuget.org/v3/index.json': This package is signed but not by a trusted signer.	Joveler.Compression.XZ	C:\Users\rp_to\Source\Repos\Joveler.Compression\Joveler.Compression.XZ\Joveler.Compression.XZ.csproj	1

**Comment by ied206** [comment]
I have never signed `Joveler.DynLoader` library, which I also wrote.
Does this error still happen on your machine? I have investigated the issue, such as the [NuGet repo issue](https://github.com/NuGet/Home/issues/11605), but could not reproduce the issue.
